name: fin_the_pen_app
description: 핀더팬 앱입니다.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  sizer: ^2.0.15
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  shimmer_animation: ^2.1.0+1
  modal_bottom_sheet: ^2.1.2
  flutter_sticky_header: ^0.6.5
  table_calendar: ^3.0.8
  bottom_sheet: ^3.1.2
  flutter_phoenix: ^1.1.1
  fluttertoast: ^8.2.2
  syncfusion_flutter_datepicker: ^21.2.3
  image_picker: ^1.0.1
  smooth_page_indicator: ^1.1.0
  pattern_formatter: ^2.0.0
  mask_text_input_formatter: ^2.5.0
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  infinite_scroll_pagination: ^3.2.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - lib/_assets/images/vectors/
    - lib/_assets/images/vectors/social_login/
    - lib/_assets/images/bitmaps/
  fonts:
    - family: IM_Hyemin
      fonts:
        - asset: lib/_assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: lib/_assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: lib/_assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: lib/_assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: lib/_assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: lib/_assets/fonts/Pretendard-Black.otf
          weight: 900
  uses-material-design: true

  